# YouTube Data API Configuration
youtube.api.key=YOUR_API_KEY_HERE
# For security reasons, in the publicly released version, we have changed the key to a placeholder (YOUR_API_KEY_HERE).
# Please fill it in yourself. You can click the Cloud Console link set up API directly in the README.
youtube.api.base.url=https://www.googleapis.com/youtube/v3
youtube.api.timeout.ms=3000
youtube.api.max.retries=2

# Cache Configuration
cache.ttl.minutes=30

# Fallback Configuration
fallback.enabled=true